format = '''
[โญ[๎ฏ](bold red)$directoryยทยทยทยทยทยทยทยทยทยทยทยทยทยทยทยทยทยทยทยทยทยทยทยทยทยทยทยทยทยทยทยทยทยทยทยทยทยทยทยทยทยทยทยทยทยทยทยทยทยทยทยทยทยทยทยทยทยทยทยทยทยทยทยทยทยทยทยทยทยทยทยทยทยทยทยทยทยทยทยทยทยทยทยทยทยท$time](bold black)
[โฐ](bold black)[โฏ](bold green) '''

[directory]
home_symbol = '๐|โผ'
truncation_length = 8
truncation_symbol = ''
style = 'bold blue'

[time]
format = 'at [$time] (style) '
use_12hr = false
utc_time_offset = 'local'
style = 'bold cyan'

[git_branch]
symbol = '๎ฅ'
truncation_length = 4
truncation_symbol = ''
